[application]
name = "scopa"
default_platform = "web"
asset_dir = "assets"

[web.app]
title = "Scopa Scorer"
#uncomment for gh-pages deploy.
#base_path = "scopa/app"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "io.github.nigeleke"
publisher = "Nigel Eke"
icon = [
    "icons/icon.icns",
    "icons/icon.ico",
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/256x256.png",
    "icons/512x512.png"
]
